//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThingsToDo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ThingsToDo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThingsToDo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThingsToDo.Resources.ThingsToDo", typeof(ThingsToDo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error!.
        /// </summary>
        public static string Global_InternalServerError {
            get {
                return ResourceManager.GetString("Global_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        public static string lblAddCategory {
            get {
                return ResourceManager.GetString("lblAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add task.
        /// </summary>
        public static string lblAddTask {
            get {
                return ResourceManager.GetString("lblAddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string lblAll {
            get {
                return ResourceManager.GetString("lblAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axies.
        /// </summary>
        public static string lblAxies {
            get {
                return ResourceManager.GetString("lblAxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string lblBy {
            get {
                return ResourceManager.GetString("lblBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string lblCategories {
            get {
                return ResourceManager.GetString("lblCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string lblClose {
            get {
                return ResourceManager.GetString("lblClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string lblCreatedDate {
            get {
                return ResourceManager.GetString("lblCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string lblError {
            get {
                return ResourceManager.GetString("lblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading statistics.
        /// </summary>
        public static string lblErrorLoadingStatistics {
            get {
                return ResourceManager.GetString("lblErrorLoadingStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string lblErrorOccurred {
            get {
                return ResourceManager.GetString("lblErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string lblFinished {
            get {
                return ResourceManager.GetString("lblFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished date.
        /// </summary>
        public static string lblFinishedDate {
            get {
                return ResourceManager.GetString("lblFinishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished tasks.
        /// </summary>
        public static string lblFinishedTasks {
            get {
                return ResourceManager.GetString("lblFinishedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        public static string lblFromDate {
            get {
                return ResourceManager.GetString("lblFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string lblHigh {
            get {
                return ResourceManager.GetString("lblHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest.
        /// </summary>
        public static string lblHighest {
            get {
                return ResourceManager.GetString("lblHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days.
        /// </summary>
        public static string lblLast7Days {
            get {
                return ResourceManager.GetString("lblLast7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string lblLockedOut {
            get {
                return ResourceManager.GetString("lblLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string lblLockedOutMessage {
            get {
                return ResourceManager.GetString("lblLockedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string lblLogOut {
            get {
                return ResourceManager.GetString("lblLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string lblLow {
            get {
                return ResourceManager.GetString("lblLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest.
        /// </summary>
        public static string lblLowest {
            get {
                return ResourceManager.GetString("lblLowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string lblMonthly {
            get {
                return ResourceManager.GetString("lblMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My finished tasks.
        /// </summary>
        public static string lblMyFinishedTasks {
            get {
                return ResourceManager.GetString("lblMyFinishedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My removed tasks.
        /// </summary>
        public static string lblMyRemovedTasks {
            get {
                return ResourceManager.GetString("lblMyRemovedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string lblNew {
            get {
                return ResourceManager.GetString("lblNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string lblNormal {
            get {
                return ResourceManager.GetString("lblNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie.
        /// </summary>
        public static string lblPie {
            get {
                return ResourceManager.GetString("lblPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string lblPriority {
            get {
                return ResourceManager.GetString("lblPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly.
        /// </summary>
        public static string lblQuarterly {
            get {
                return ResourceManager.GetString("lblQuarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        public static string lblRemoved {
            get {
                return ResourceManager.GetString("lblRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed tasks.
        /// </summary>
        public static string lblRemovedTasks {
            get {
                return ResourceManager.GetString("lblRemovedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string lblRequiredField {
            get {
                return ResourceManager.GetString("lblRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select priority.
        /// </summary>
        public static string lblSelectPriority {
            get {
                return ResourceManager.GetString("lblSelectPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string lblStatistics {
            get {
                return ResourceManager.GetString("lblStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string lblTask {
            get {
                return ResourceManager.GetString("lblTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task created successfully!.
        /// </summary>
        public static string lblTaskCreated {
            get {
                return ResourceManager.GetString("lblTaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string lblTasks {
            get {
                return ResourceManager.GetString("lblTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task statistics.
        /// </summary>
        public static string lblTaskStatistics {
            get {
                return ResourceManager.GetString("lblTaskStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required!.
        /// </summary>
        public static string lblTitleRequired {
            get {
                return ResourceManager.GetString("lblTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until date.
        /// </summary>
        public static string lblUntilDate {
            get {
                return ResourceManager.GetString("lblUntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string lblWeekly {
            get {
                return ResourceManager.GetString("lblWeekly", resourceCulture);
            }
        }
    }
}
